# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kythe/proto/storage_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 1, "", "kythe/proto/storage_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n!kythe/proto/storage_service.proto\x12\x0bkythe.proto\x1a\x19kythe/proto/storage.proto2\xbf\x01\n\nGraphStore\x12\x38\n\x04Read\x12\x18.kythe.proto.ReadRequest\x1a\x12.kythe.proto.Entry"\x00\x30\x01\x12\x38\n\x04Scan\x12\x18.kythe.proto.ScanRequest\x1a\x12.kythe.proto.Entry"\x00\x30\x01\x12=\n\x05Write\x12\x19.kythe.proto.WriteRequest\x1a\x17.kythe.proto.WriteReply"\x00\x32\x8e\x01\n\x11ShardedGraphStore\x12=\n\x05\x43ount\x12\x19.kythe.proto.CountRequest\x1a\x17.kythe.proto.CountReply"\x00\x12:\n\x05Shard\x12\x19.kythe.proto.ShardRequest\x1a\x12.kythe.proto.Entry"\x00\x30\x01\x42P\n\x1f\x63om.google.devtools.kythe.protoZ-kythe.io/kythe/proto/storage_service_go_protob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "kythe.proto.storage_service_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\037com.google.devtools.kythe.protoZ-kythe.io/kythe/proto/storage_service_go_proto"
    _globals["_GRAPHSTORE"]._serialized_start = 78
    _globals["_GRAPHSTORE"]._serialized_end = 269
    _globals["_SHARDEDGRAPHSTORE"]._serialized_start = 272
    _globals["_SHARDEDGRAPHSTORE"]._serialized_end = 414
# @@protoc_insertion_point(module_scope)
