all: && sync reformat lint test

sync:
    uv sync --all-extras

reformat:
    uv run ruff format
    uv run ruff check --fix

lint:
    uv run ruff format --check
    uv run ruff check

test:
    uv run pytest -svv
