all: && sync reformat lint test

sync:
    uv sync --all-extras

reformat:
    uv run ruff format
    uv run ruff check --fix

lint:
    uv run ruff format --check
    uv run ruff check
    uv run mypy

test:
    # To debug
    # uv run pytest -svv --log-cli-level=DEBUG --runintegration

    # To save unit test results
    # PYTEST_DEBUG_TEMPROOT="/crs_scratch/" uv run pytest -svv --runintegration

    # To run tests
    uv run pytest -svv --runintegration
