# Pre-commit hooks for Buttercup CRS
# See https://pre-commit.com for more information
#
# This configuration integrates with the project's existing linting infrastructure
# to ensure consistency between pre-commit, local development, and CI.

default_language_version:
  python: python3

repos:
  # Only include checks that ruff doesn't handle
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: 'deployment/k8s/.*\.(yaml|yml)$'
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]

  # Use local hooks that leverage the project's existing infrastructure
  - repo: local
    hooks:
      # Format check using project's ruff via uv
      - id: ruff-format
        name: ruff format
        entry: bash -c 'for file in "$@"; do abs_file="$(pwd)/$file"; dir=$(dirname "$abs_file"); while [[ "$dir" != "/" ]]; do if [[ -f "$dir/pyproject.toml" ]] && [[ "$(basename "$dir")" =~ ^(common|orchestrator|fuzzer|patcher|program-model|seed-gen)$ ]]; then (cd "$dir" && uv run ruff format "$abs_file") || exit 1; break; fi; dir=$(dirname "$dir"); done; done' --
        language: system
        types: [python]
        require_serial: false

      # Lint check using project's ruff via uv
      - id: ruff-check
        name: ruff check
        entry: bash -c 'for file in "$@"; do abs_file="$(pwd)/$file"; dir=$(dirname "$abs_file"); while [[ "$dir" != "/" ]]; do if [[ -f "$dir/pyproject.toml" ]] && [[ "$(basename "$dir")" =~ ^(common|orchestrator|fuzzer|patcher|program-model|seed-gen)$ ]]; then (cd "$dir" && uv run ruff check --fix "$abs_file") || exit 1; break; fi; dir=$(dirname "$dir"); done; done' --
        language: system
        types: [python]
        require_serial: false

# Global exclusions for files that should never be checked
exclude: |
  (?x)^(
    external/.*|
    .*\.pb\.py|
    .*_pb2\.py|
    .*_pb2_grpc\.py|
    .*/\.venv/.*|
    .*/\.mypy_cache/.*|
    .*/\.ruff_cache/.*|
    .*/\.pytest_cache/.*
  )$

# Don't fail fast - show all issues
fail_fast: false