# Pre-commit hooks for Buttercup CRS
# See https://pre-commit.com for more information
#
# This configuration delegates all Python linting to the project's Makefile,
# ensuring complete consistency between pre-commit, local development, and CI.

minimum_pre_commit_version: '2.20.0'
default_language_version:
  python: python3

repos:
  # Non-Python file validation (ruff doesn't handle these)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: 'deployment/k8s/.*\.(yaml|yml)$'
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]

  # Python linting via project script
  - repo: local
    hooks:
      - id: lint-python
        name: Lint Python files
        entry: scripts/lint-changed-files.sh fix
        language: system
        types: [python]
        pass_filenames: true
        require_serial: true

# Global exclusions for files that should never be checked
exclude: |
  (?x)^(
    external/.*|
    .*\.pb\.py|
    .*_pb2\.py|
    .*_pb2_grpc\.py|
    .*/\.venv/.*|
    .*/\.mypy_cache/.*|
    .*/\.ruff_cache/.*|
    .*/\.pytest_cache/.*|
    __pycache__/.*
  )$

# Configuration
fail_fast: false
ci:
  autofix_prs: true
  autoupdate_schedule: weekly