enabled: true

resources:
  limits:
    cpu: 8000m
    memory: 8192Mi
  requests:
    cpu: 500m
    memory: 512Mi

timeout: 900
timer: 5000
max_local_files: 500

# Fuzzer runner side container configuration
fuzzerRunner:
  enabled: true
  port: 8000

mergerBot:
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 256Mi
