services:
  litellm:
    image: ghcr.io/berriai/litellm:litellm_stable_release_branch-v1.57.8-stable
    configs:
      - source: litellm_config
        target: /app/config.yaml
    env_file: .env
    ports:
      - "127.0.0.1:8080:8080"
    command: ["--config", "/app/config.yaml", "--port", "8080"]

configs:
  litellm_config:
    file: ./litellm_config.yaml
