# Mock Competition API Configuration
# Set to false to disable the mock competition API entirely
enabled: true

replicaCount: 1

service:
  port: 1323

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 100m
    memory: 256Mi 
