update-apis:
	@echo "Updating Competition/CRS APIs..."
	@./scripts/update_apis.sh $(shell pwd)

generate-competition-api:
	@echo "Generating FastAPI Competition API skeleton..."
	@./scripts/generate_competition_api.sh $(shell pwd)
