{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: ui
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ui
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: {{ .Release.Name }} 
{{- end }} 
