#!/bin/bash
# Migration script to transition from individual bots to unified fuzzer

echo "Migration Guide: Individual Bots to Unified Fuzzer"
echo "=================================================="
echo ""
echo "The unified fuzzer combines all fuzzing functionality into a single service:"
echo "- Builder Bot"
echo "- Fuzzer Bot" 
echo "- Coverage Bot"
echo "- Tracer Bot"
echo ""
echo "Key changes:"
echo "1. Single Docker image: Use 'unified_fuzzer.Dockerfile' instead of 'runner_image.Dockerfile'"
echo "2. Single service deployment instead of 4 separate services"
echo "3. Internal communication via Python queues (more efficient)"
echo "4. Redis only used for external task coordination"
echo ""
echo "Environment Variables:"
echo "The unified fuzzer uses prefixed environment variables:"
echo "- BUTTERCUP_UNIFIED_FUZZER_REDIS_URL"
echo "- BUTTERCUP_UNIFIED_FUZZER_NUM_FUZZER_WORKERS (default: 2)"
echo "- BUTTERCUP_UNIFIED_FUZZER_BUILDER_* (builder settings)"
echo "- BUTTERCUP_UNIFIED_FUZZER_FUZZER_* (fuzzer settings)"
echo "- BUTTERCUP_UNIFIED_FUZZER_COVERAGE_* (coverage settings)"
echo "- BUTTERCUP_UNIFIED_FUZZER_TRACER_* (tracer settings)"
echo ""
echo "To build the unified fuzzer image:"
echo "docker build -f dockerfiles/unified_fuzzer.Dockerfile -t buttercup-unified-fuzzer ."
echo ""
echo "To run the unified fuzzer:"
echo "docker run --name unified-fuzzer buttercup-unified-fuzzer"
echo ""
echo "After successful testing, the individual bot files can be removed:"
echo "- fuzzing_infra/builder_bot.py"
echo "- fuzzing_infra/fuzzer_bot.py"  
echo "- fuzzing_infra/coverage_bot.py"
echo "- fuzzing_infra/tracer_bot.py"