[project]
name = "fuzzing-infra"
version = "0.1.0"
description = ""
authors = [
    {name = "Ian Smith",email = "ian.smith@trailofbits.com"}
]
readme = "README.md"
requires-python = ">=3.9,<=3.10"
dependencies = [
    "protobuf (>=3.20, <=3.20.3)",
    "redis (>=5.2.1,<6.0.0)",
    "clusterfuzz==2.6.0",
    "common",
]

[tool.uv.sources]
common = { path = "../common", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["src/buttercup"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
