# coding: utf-8

"""
    Example Competition API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class TypesPatchSubmission(BaseModel):
    """
    TypesPatchSubmission
    """ # noqa: E501
    description: Optional[Annotated[str, Field(strict=True, max_length=131072)]] = Field(default=None, description="Optional plain text reasoning for the assessment  128KiB max size")
    patch: StrictStr = Field(description="Base64 encoded patch in unified diff format  100KiB max size before Base64 encoding")
    sarif_id: Optional[StrictStr] = Field(default=None, description="Optional ID of SARIF Broadcast this patch is associated with")
    vuln_id: Optional[StrictStr] = Field(default=None, description="Optional ID of Vuln this patch is associated with")
    __properties: ClassVar[List[str]] = ["description", "patch", "sarif_id", "vuln_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TypesPatchSubmission from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TypesPatchSubmission from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "description": obj.get("description"),
            "patch": obj.get("patch"),
            "sarif_id": obj.get("sarif_id"),
            "vuln_id": obj.get("vuln_id")
        })
        return _obj


