# coding: utf-8

"""
    Example Competition API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TypesSubmissionStatus(str, Enum):
    """
    TypesSubmissionStatus
    """

    """
    allowed enum values
    """
    SubmissionStatusAccepted = 'accepted'
    SubmissionStatusPassed = 'passed'
    SubmissionStatusFailed = 'failed'
    SubmissionStatusDeadlineExceeded = 'deadline_exceeded'
    SubmissionStatusErrored = 'errored'
    SubmissionStatusInconclusive = 'inconclusive'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TypesSubmissionStatus from a JSON string"""
        return cls(json.loads(json_str))


