from typing import TypeAlias

# We are using this type instead of msg_pb2.BuildType for type hints.
# The reason is that msg_pb2.BuildType is generated by protobuf and while
# it behaves like an enum it is not a proper enum class. Instead, it is a
# EnumTypeWrapper instance (some class belonging to protobuf). Hence, using
# msg_pb2 directly in type hints results in runtime errors
BuildType: TypeAlias = int