# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orchestrator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12orchestrator.proto\x12\x0corchestrator\"\xa8\x03\n\x04Task\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x14\n\x0cmessage_time\x18\x02 \x01(\x03\x12\x0f\n\x07task_id\x18\x03 \x01(\t\x12.\n\ttask_type\x18\x04 \x01(\x0e\x32\x1b.orchestrator.Task.TaskType\x12+\n\x07sources\x18\x05 \x03(\x0b\x32\x1a.orchestrator.SourceDetail\x12\x10\n\x08\x64\x65\x61\x64line\x18\x06 \x01(\x03\x12\x32\n\x0btask_status\x18\x07 \x01(\x0e\x32\x1d.orchestrator.Task.TaskStatus\"3\n\x08TaskType\x12\x12\n\x0eTASK_TYPE_FULL\x10\x00\x12\x13\n\x0fTASK_TYPE_DELTA\x10\x01\"\x8c\x01\n\nTaskStatus\x12\x17\n\x13TASK_STATUS_PENDING\x10\x00\x12\x17\n\x13TASK_STATUS_RUNNING\x10\x01\x12\x19\n\x15TASK_STATUS_SUCCEEDED\x10\x02\x12\x16\n\x12TASK_STATUS_FAILED\x10\x03\x12\x19\n\x15TASK_STATUS_CANCELLED\x10\x04\"\xbf\x01\n\x0cSourceDetail\x12\x0e\n\x06sha256\x18\x01 \x01(\t\x12:\n\x0bsource_type\x18\x02 \x01(\x0e\x32%.orchestrator.SourceDetail.SourceType\x12\x0b\n\x03url\x18\x03 \x01(\t\"V\n\nSourceType\x12\x14\n\x10SOURCE_TYPE_REPO\x10\x00\x12\x1c\n\x18SOURCE_TYPE_FUZZ_TOOLING\x10\x01\x12\x14\n\x10SOURCE_TYPE_DIFF\x10\x02\"\x1f\n\x0cTaskDownload\x12\x0f\n\x07task_id\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TASK._serialized_start=37
  _TASK._serialized_end=461
  _TASK_TASKTYPE._serialized_start=267
  _TASK_TASKTYPE._serialized_end=318
  _TASK_TASKSTATUS._serialized_start=321
  _TASK_TASKSTATUS._serialized_end=461
  _SOURCEDETAIL._serialized_start=464
  _SOURCEDETAIL._serialized_end=655
  _SOURCEDETAIL_SOURCETYPE._serialized_start=569
  _SOURCEDETAIL_SOURCETYPE._serialized_end=655
  _TASKDOWNLOAD._serialized_start=657
  _TASKDOWNLOAD._serialized_end=688
# @@protoc_insertion_point(module_scope)
