# generated by fastapi-codegen:
#   filename:  /tmp/tmp.2oPWWGSa8F/openapi.json
#   timestamp: 2025-01-23T10:58:54+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class SourceType(Enum):
    SourceTypeRepo = 'repo'
    SourceTypeFuzzTooling = 'fuzz-tooling'
    SourceTypeDiff = 'diff'


class StatusTasksState(BaseModel):
    canceled: int
    errored: int
    pending: int
    running: int
    succeeded: int


class TaskType(Enum):
    TaskTypeFull = 'full'
    TaskTypeDelta = 'delta'


class VulnDetail(BaseModel):
    sarif: Dict[str, Any] = Field(
        ...,
        description='SARIF Report compliant with "https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/schemas/sarif-schema-2.1.0.json"',
    )
    task_id: str
    vuln_id: str


class SourceDetail(BaseModel):
    sha256: str
    type: SourceType
    url: str


class StatusState(BaseModel):
    tasks: StatusTasksState


class TaskDetail(BaseModel):
    deadline: int
    source: List[SourceDetail]
    task_id: str
    type: TaskType


class VulnBroadcast(BaseModel):
    message_id: str
    message_time: int
    vulns: List[VulnDetail]


class Status(BaseModel):
    details: Optional[Dict[str, Dict[str, Any]]] = Field(
        None,
        description='Keep in mind this endpoint is unauthenticated. Do not place sensitive details in this object. This is optional arbitrary content. This may be logged in error cases, but is mainly for interactive troubleshooting.',
    )
    ready: bool
    state: StatusState
    version: str = Field(
        ...,
        description='Version string for verification and reproducibility. Git commit, SemVer, etc...',
    )


class Task(BaseModel):
    message_id: str
    message_time: int
    tasks: List[TaskDetail]
