# coding: utf-8

"""
Example Competition API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.4.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from buttercup.orchestrator.competition_api_client.api.bundle_api import BundleApi


class TestBundleApi(unittest.TestCase):
    """BundleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BundleApi()

    def tearDown(self) -> None:
        pass

    def test_v1_task_task_id_bundle_bundle_id_delete(self) -> None:
        """Test case for v1_task_task_id_bundle_bundle_id_delete

        Delete Bundle
        """
        pass

    def test_v1_task_task_id_bundle_bundle_id_get(self) -> None:
        """Test case for v1_task_task_id_bundle_bundle_id_get

        Get Bundle
        """
        pass

    def test_v1_task_task_id_bundle_bundle_id_patch(self) -> None:
        """Test case for v1_task_task_id_bundle_bundle_id_patch

        Update Bundle
        """
        pass

    def test_v1_task_task_id_bundle_post(self) -> None:
        """Test case for v1_task_task_id_bundle_post

        Submit Bundle
        """
        pass


if __name__ == "__main__":
    unittest.main()
