# coding: utf-8

"""
    Example Competition API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from competition_api_client.models.types_vuln_submission_response import TypesVulnSubmissionResponse

class TestTypesVulnSubmissionResponse(unittest.TestCase):
    """TypesVulnSubmissionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TypesVulnSubmissionResponse:
        """Test TypesVulnSubmissionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TypesVulnSubmissionResponse`
        """
        model = TypesVulnSubmissionResponse()
        if include_optional:
            return TypesVulnSubmissionResponse(
                status = 'accepted',
                vuln_id = ''
            )
        else:
            return TypesVulnSubmissionResponse(
                status = 'accepted',
                vuln_id = '',
        )
        """

    def testTypesVulnSubmissionResponse(self):
        """Test TypesVulnSubmissionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
