# coding: utf-8

"""
    Example Competition API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buttercup.orchestrator.competition_api_client.models.types_vuln_submission import TypesVulnSubmission

class TestTypesVulnSubmission(unittest.TestCase):
    """TypesVulnSubmission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TypesVulnSubmission:
        """Test TypesVulnSubmission
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TypesVulnSubmission`
        """
        model = TypesVulnSubmission()
        if include_optional:
            return TypesVulnSubmission(
                architecture = '',
                data_file = '',
                harness_name = '',
                sanitizer = '',
                sarif = None
            )
        else:
            return TypesVulnSubmission(
                architecture = '',
                data_file = '',
                harness_name = '',
                sanitizer = '',
        )
        """

    def testTypesVulnSubmission(self):
        """Test TypesVulnSubmission"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
