# coding: utf-8

"""
    Example Competition API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buttercup.orchestrator.competition_api_client.models.types_bundle_submission_response_verbose import TypesBundleSubmissionResponseVerbose

class TestTypesBundleSubmissionResponseVerbose(unittest.TestCase):
    """TypesBundleSubmissionResponseVerbose unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TypesBundleSubmissionResponseVerbose:
        """Test TypesBundleSubmissionResponseVerbose
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TypesBundleSubmissionResponseVerbose`
        """
        model = TypesBundleSubmissionResponseVerbose()
        if include_optional:
            return TypesBundleSubmissionResponseVerbose(
                broadcast_sarif_id = '',
                bundle_id = '',
                description = '',
                freeform_id = '',
                patch_id = '',
                pov_id = '',
                status = 'accepted',
                submitted_sarif_id = ''
            )
        else:
            return TypesBundleSubmissionResponseVerbose(
                bundle_id = '',
                status = 'accepted',
        )
        """

    def testTypesBundleSubmissionResponseVerbose(self):
        """Test TypesBundleSubmissionResponseVerbose"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
