# coding: utf-8

"""
Example Competition API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.4.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from buttercup.orchestrator.competition_api_client.api.request_api import RequestApi


class TestRequestApi(unittest.TestCase):
    """RequestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RequestApi()

    def tearDown(self) -> None:
        pass

    def test_v1_request_challenge_name_post(self) -> None:
        """Test case for v1_request_challenge_name_post

        Send a task to the source of this request
        """
        pass

    def test_v1_request_list_get(self) -> None:
        """Test case for v1_request_list_get

        Get a list of available challenges to task
        """
        pass


if __name__ == "__main__":
    unittest.main()
