# coding: utf-8

"""
    Example Competition API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buttercup.orchestrator.competition_api_client.api.patch_api import PatchApi


class TestPatchApi(unittest.TestCase):
    """PatchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PatchApi()

    def tearDown(self) -> None:
        pass

    def test_v1_task_task_id_patch_patch_id_get(self) -> None:
        """Test case for v1_task_task_id_patch_patch_id_get

        Patch Status
        """
        pass

    def test_v1_task_task_id_patch_post(self) -> None:
        """Test case for v1_task_task_id_patch_post

        Submit Patch
        """
        pass


if __name__ == '__main__':
    unittest.main()
