# coding: utf-8

"""
Example Competition API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.4.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from buttercup.orchestrator.competition_api_client.api.broadcast_sarif_assessment_api import BroadcastSarifAssessmentApi


class TestBroadcastSarifAssessmentApi(unittest.TestCase):
    """BroadcastSarifAssessmentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BroadcastSarifAssessmentApi()

    def tearDown(self) -> None:
        pass

    def test_v1_task_task_id_broadcast_sarif_assessment_broadcast_sarif_id_post(self) -> None:
        """Test case for v1_task_task_id_broadcast_sarif_assessment_broadcast_sarif_id_post

        Submit a SARIF Assessment
        """
        pass


if __name__ == "__main__":
    unittest.main()
