# coding: utf-8

"""
Example Competition API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.4.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from buttercup.orchestrator.competition_api_client.api.ping_api import PingApi


class TestPingApi(unittest.TestCase):
    """PingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PingApi()

    def tearDown(self) -> None:
        pass

    def test_v1_ping_get(self) -> None:
        """Test case for v1_ping_get

        Test authentication creds and network connectivity
        """
        pass


if __name__ == "__main__":
    unittest.main()
