"""
Example Competition API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.4.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest


class TestTypesSubmissionStatus(unittest.TestCase):
    """TypesSubmissionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypesSubmissionStatus(self):
        """Test TypesSubmissionStatus"""
        # inst = TypesSubmissionStatus()


if __name__ == "__main__":
    unittest.main()
