# coding: utf-8

"""
Example Competition API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from buttercup.orchestrator.competition_api_client.api.feeform_api import FeeformApi


class TestFeeformApi(unittest.TestCase):
    """FeeformApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FeeformApi()

    def tearDown(self) -> None:
        pass

    def test_v1_task_task_id_freeform_post(self) -> None:
        """Test case for v1_task_task_id_freeform_post

        Submit Freeform
        """
        pass


if __name__ == "__main__":
    unittest.main()
