# coding: utf-8

"""
    Example Competition API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buttercup.orchestrator.competition_api_client.models.types_freeform_response import TypesFreeformResponse

class TestTypesFreeformResponse(unittest.TestCase):
    """TypesFreeformResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TypesFreeformResponse:
        """Test TypesFreeformResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TypesFreeformResponse`
        """
        model = TypesFreeformResponse()
        if include_optional:
            return TypesFreeformResponse(
                freeform_id = '',
                status = 'accepted'
            )
        else:
            return TypesFreeformResponse(
                freeform_id = '',
                status = 'accepted',
        )
        """

    def testTypesFreeformResponse(self):
        """Test TypesFreeformResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
