# coding: utf-8

"""
Example Competition API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.4.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from buttercup.orchestrator.competition_api_client.api.pov_api import PovApi


class TestPovApi(unittest.TestCase):
    """PovApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PovApi()

    def tearDown(self) -> None:
        pass

    def test_v1_task_task_id_pov_post(self) -> None:
        """Test case for v1_task_task_id_pov_post

        Submit Vulnerability
        """
        pass

    def test_v1_task_task_id_pov_pov_id_get(self) -> None:
        """Test case for v1_task_task_id_pov_pov_id_get

        Vulnerability Status
        """
        pass


if __name__ == "__main__":
    unittest.main()
